#!/bin/bash
# Script: Arrancar BFF + Chakra en dev local (2 terminales)

echo "🚀 QA Pausa 1️⃣ — Dev local (localhost)"
echo ""
echo "=== TERMINAL 1: BFF (puerto 3000) ==="
echo "Ejecuta en otra terminal (desde raiz del proyecto):"
echo "  npm run dev"
echo ""
echo "=== TERMINAL 2: Chakra (puerto 5174) ==="
echo "Ejecuta en otra terminal (desde raiz del proyecto):"
echo "  npm run dev:chakra"
echo ""
echo "=== Verificar que funciona ==="
echo "1. Abre http://localhost:5174 en navegador"
echo "2. Debería cargar Chakra UI"
echo "3. Click 'Login' → intenta conectar a localhost:3000"
echo "4. Entra: demo@empresa.com / demo1234"
echo ""
echo "=== Troubleshooting ==="
echo "Error CORS? → revisar que BFF está en localhost:3000"
echo "Error 404? → revisar .env.local VITE_API_BASE_URL"
echo "Module not found? → npm install en ambas carpetas"
echo ""
